spring:
  application:
    name: accidents-bh-backend

  datasource:
    url: jdbc:sqlite:./data/accidents.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    br.ufmg.tcc: DEBUG
    org.springframework.web: INFO
